# This is a basic workflow to help you get started with Actions

name: Deploy Picote

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Install global firebase
      run: npm i -g firebase-tools
    - name: Build site
      run: npm run build --prod
    - name: Build site
      run: firebase deploy --token $FIREBASE_TOKEN
